seeds: random

prompts:
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."
  - "a cat is walking forward,a dog is barking."

n_prompts:
  - "sketches, worst quality, low quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet, extra feets,incongruous appearance,distortion,deformation, "

path_to_first_frames:
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"
  - "/nvme-ssd/yanyi/code/image/test_100/019.png"