seeds: 442

prompts:
  - "a dog is barking,a rabbit is chewing."
  - "a cat is nodding head,a dog is barking."
  - "a mouse is falling down,a dog is standing up."
  - "the left cat is nodding head,the right cat is walking."
  - "a cat is sleeping,a rabbit is chewing."
  - "a dog is barking,a duck is walking forward."
  - "a duck is shaking head,a dog is walking."
  - "a duck is nodding its head,a dog is barking."
  - "a dog is barking,a cat is walking forward."
  - "a girl is smiling,a duck is nodding its head."
  - "the left duck is nodding head,the right duck is walking."
  - "a dog is nodding head,a duck is quacking."
  - "a cat is meowing,a dog is sleeping."
  - "a duck is eating food,a pig is raising head."
  - "the left lion is roaring,the right lion is walking."
  - "a duck is quacking,a chicken is turning backing."
  - "a duck is standing up,a pig is barking."
  - "a pig is downing head,a dog is barking."
  - "a chicken is nodding head,a duck is walking."
  - "the left dog is barking,a right dog is falling down."
  - "a cat is walking,a dog is barking."
  - "a cat is walking,a dog is barking."
  - "a cat is downing head, a dog is barking."
  - "a dog is barking,a cat is walking forward."
  - "a dog is barking,a cat is nodding up and down."
  - "a cat is nodding up and down,a dog is barking."
  - "a dog is barking,a cat is smiling."
  - "a cat is walking forward,a dog is barking."
  - "a cat is meowing,a dog is walking forward."
  - "a cat is meowing,a dog is walking forward."
  - "a cat is nodding up and down,a dog is barking."
  - "a cat is downing head,a dog is smiling."
  - "a cat is meowing,a dog is shaking head."
  - "a dog is barking,a cat is falling down."
  - "a cat is lifting its head,a dog is barking."
  - "a dog is barking,a cat is wagging its tail."
  - "a dog is sticking out its tongue,a girl is smiling."
  - "a dog is sleeping,a cat is meowing."
  - "a woman is smiling,a man is downing his head."
  - "a dog is sticking out its tongue,a cat is nodding head."
  - "a woman is smiling,a man is crying."
  - "a cat is lifting its head,a dog is barking."
  - "a woman is smiling,a man is crying."
  - "a dog is barking,a cat is walking."
  - "a cat is nodding head,a dog is walking."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is walking forward."
  - "a man is smilling,a woman is cryling."
  - "a cat is nodding head,a dog is walking."

n_prompts:
  - "nsfw, paintings, cartoon, anime, dark,sketches, wrong white balance,worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, extra claws,fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet,extrafeets,incongruousappearance,Distortedappearance,deformation,bad_pictures, negative_hand-neg , bad teeth, mutated hands and fingers, bad anatomy"
path_to_first_frames:
  - "/nvme-ssd/yanyi/code/image/test_45/055.png"
  - "/nvme-ssd/yanyi/code/image/test_45/056.png"
  - "/nvme-ssd/yanyi/code/image/test_45/057.png"
  - "/nvme-ssd/yanyi/code/image/test_45/058.png"
  - "/nvme-ssd/yanyi/code/image/test_45/059.png"
  - "/nvme-ssd/yanyi/code/image/test_45/060.png"
  - "/nvme-ssd/yanyi/code/image/test_45/061.png"
  - "/nvme-ssd/yanyi/code/image/test_45/062.png"
  - "/nvme-ssd/yanyi/code/image/test_45/063.png"
  - "/nvme-ssd/yanyi/code/image/test_45/064.png"
  - "/nvme-ssd/yanyi/code/image/test_45/065.png"
  - "/nvme-ssd/yanyi/code/image/test_45/066.png"
  - "/nvme-ssd/yanyi/code/image/test_45/067.png"
  - "/nvme-ssd/yanyi/code/image/test_45/068.png"
  - "/nvme-ssd/yanyi/code/image/test_45/069.png"
  - "/nvme-ssd/yanyi/code/image/test_45/070.png"
  - "/nvme-ssd/yanyi/code/image/test_45/071.png"
  - "/nvme-ssd/yanyi/code/image/test_45/072.png"
  - "/nvme-ssd/yanyi/code/image/test_45/073.png"
  - "/nvme-ssd/yanyi/code/image/test_45/074.png"
  - "/nvme-ssd/yanyi/code/image/test_45/075.png"
  - "/nvme-ssd/yanyi/code/image/test_45/076.png"
  - "/nvme-ssd/yanyi/code/image/test_45/077.png"
  - "/nvme-ssd/yanyi/code/image/test_45/078.png"
  - "/nvme-ssd/yanyi/code/image/test_45/079.png"
  - "/nvme-ssd/yanyi/code/image/test_45/080.png"
  - "/nvme-ssd/yanyi/code/image/test_45/081.png"
  - "/nvme-ssd/yanyi/code/image/test_45/082.png"
  - "/nvme-ssd/yanyi/code/image/test_45/083.png"
  - "/nvme-ssd/yanyi/code/image/test_45/084.png"
  - "/nvme-ssd/yanyi/code/image/test_45/085.png"
  - "/nvme-ssd/yanyi/code/image/test_45/086.png"
  - "/nvme-ssd/yanyi/code/image/test_45/087.png"
  - "/nvme-ssd/yanyi/code/image/test_45/088.png"
  - "/nvme-ssd/yanyi/code/image/test_45/089.png"
  - "/nvme-ssd/yanyi/code/image/test_45/090.png"
  - "/nvme-ssd/yanyi/code/image/test_45/091.png"
  - "/nvme-ssd/yanyi/code/image/test_45/092.png"
  - "/nvme-ssd/yanyi/code/image/test_45/093.png"
  - "/nvme-ssd/yanyi/code/image/test_45/094.png"
  - "/nvme-ssd/yanyi/code/image/test_45/095.png"
  - "/nvme-ssd/yanyi/code/image/test_45/096.png"
  - "/nvme-ssd/yanyi/code/image/test_45/097.png"
  - "/nvme-ssd/yanyi/code/image/test_45/098.png"
  - "/nvme-ssd/yanyi/code/image/test_45/099.png"
  - "/nvme-ssd/yanyi/code/image/test_45/100.png"
  - "/nvme-ssd/yanyi/code/image/test_45/101.png"
  - "/nvme-ssd/yanyi/code/image/test_45/102.png"
  - "/nvme-ssd/yanyi/code/image/test_45/103.png"