seeds: 442

prompts:
  - "a cat is nodding up and down,a dog is barking."
  - "a rabbit is chewing,a dog is barking."
  - "a chicken is nodding,a dog is barking."
  - "a dog is blinking its eyes,a girl is smiling."
  - "a dog is barking,a cat is downing head."
  - "a dog is barking,the fire hydrant is flowing water."
  - "a dog is barking,a cat is walking forward."
  - "a dog is barking,a cat is walking forward."
  - "a dog is noddding head,a cat is meowing."
  - "a dog is bowing head,a cat is shaking head."
  - "the left dog is falling down,the right dog is walking."
  - "a cat is wagging its tail,a dog is barking."
  - "a dog is nodding head,a cat is falling down."
  - "the left dog is nodding head,the right dog is barking."
  - "the left girl is smiling,the right girl is crying."
  - "a cat is wagging tail,a dog is barking."
  - "a dog is barking,a cat is sharking head."
  - "a cat is lifting its upper body,a dog is falling down."
  - "a dog is nodding head,a cat is meowing."
  - "a dog is nodding up and down,a cat is wagging tail."
  - "a cat is nodding up and down,a dog is falling down."
  - "a cat is walking forward,a dog is barking."
  - "a dog is turning its head around,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is shaking head."
  - "a dog is barking,a cat is falling down."
  - "a man is smiling,a girl is crying."
  - "a man is smiling,a girl is crying."
  - "a duck is nodding up and down,a cat is wagging tail."
  - "a duck is nodding,a pig is wagging tail."
  - "a girl is smiling,a boy is opening mouth."
  - "a girl is smiling,a boy is crying."
  - "a cow is standing up,a horse is walking."
  - "a girl is smiling,a boy is shedding tears."
  - "a girl is smiling,a dog is chewing."
  - "a girl is smiling,a dog is sticking out its tongue."
  - "a woman is smiling,a baby is shedding tears."
  - "a woman is smiling,a baby is crying loudly."
  - "a woman is smiling,a dog is barking."
  - "a man is smiling,a woman is blinking her eyes."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a rabbit is chewing,a dog is raising head."
  - "a dog is closing its mouth,a cat is meowing."
  - "a cat is meowing,a mouse is walking."
  - "a cat is meowing,a mouse is walking."
  - "a cat is meowing,a dog is nodding up and down."
  - "a cat is nodding,a dog is barking."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a chicken is turning back."
  - "a pig is wagging its tail,a dog is turning back."
  - "a dog is nodding head,a pig is raising head."
  - "a dog is barking,a cat is nodding head."
  - "a dog is barking,a cat is nodding head."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a man is smiling,a dog is barking."
  - "a woman is smiling,a dog is closing mouth."
  - "a woman is smiling,a dog is closing mouth."
  - "a man is smiling,a woman is crying."
  - "a woman is smiling,a dog is falling down."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a man is smiling,a woman is crying."
  - "a dog is barking,a cat is falling down."

n_prompts:
  - "nsfw, paintings, cartoon, anime, dark,sketches, wrong white balance,worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, extra claws,fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet,extrafeets,incongruousappearance,Distortedappearance,deformation,bad_pictures, negative_hand-neg , bad teeth, mutated hands and fingers, bad anatomy"
path_to_first_frames:
  - "/nvme-ssd/yanyi/code/image/test/000.png"
  - "/nvme-ssd/yanyi/code/image/test/001.png"
  - "/nvme-ssd/yanyi/code/image/test/002.png"
  - "/nvme-ssd/yanyi/code/image/test/003.png"
  - "/nvme-ssd/yanyi/code/image/test/004.png"
  - "/nvme-ssd/yanyi/code/image/test/005.png"
  - "/nvme-ssd/yanyi/code/image/test/006.png"
  - "/nvme-ssd/yanyi/code/image/test/007.png"
  - "/nvme-ssd/yanyi/code/image/test/008.png"
  - "/nvme-ssd/yanyi/code/image/test/009.png"
  - "/nvme-ssd/yanyi/code/image/test/010.png"
  - "/nvme-ssd/yanyi/code/image/test/011.png"
  - "/nvme-ssd/yanyi/code/image/test/012.png"
  - "/nvme-ssd/yanyi/code/image/test/013.png"
  - "/nvme-ssd/yanyi/code/image/test/014.png"
  - "/nvme-ssd/yanyi/code/image/test/015.png"
  - "/nvme-ssd/yanyi/code/image/test/016.png"
  - "/nvme-ssd/yanyi/code/image/test/017.png"
  - "/nvme-ssd/yanyi/code/image/test/018.png"
  - "/nvme-ssd/yanyi/code/image/test/019.png"
  - "/nvme-ssd/yanyi/code/image/test/020.png"
  - "/nvme-ssd/yanyi/code/image/test/021.png"
  - "/nvme-ssd/yanyi/code/image/test/022.png"
  - "/nvme-ssd/yanyi/code/image/test/023.png"
  - "/nvme-ssd/yanyi/code/image/test/024.png"
  - "/nvme-ssd/yanyi/code/image/test/025.png"
  - "/nvme-ssd/yanyi/code/image/test/026.png"
  - "/nvme-ssd/yanyi/code/image/test/027.png"
  - "/nvme-ssd/yanyi/code/image/test/028.png"
  - "/nvme-ssd/yanyi/code/image/test/029.png"
  - "/nvme-ssd/yanyi/code/image/test/030.png"
  - "/nvme-ssd/yanyi/code/image/test/031.png"
  - "/nvme-ssd/yanyi/code/image/test/032.png"
  - "/nvme-ssd/yanyi/code/image/test/033.png"
  - "/nvme-ssd/yanyi/code/image/test/034.png"
  - "/nvme-ssd/yanyi/code/image/test/035.png"
  - "/nvme-ssd/yanyi/code/image/test/036.png"
  - "/nvme-ssd/yanyi/code/image/test/037.png"
  - "/nvme-ssd/yanyi/code/image/test/038.png"
  - "/nvme-ssd/yanyi/code/image/test/039.png"
  - "/nvme-ssd/yanyi/code/image/test/040.png"
  - "/nvme-ssd/yanyi/code/image/test/041.png"
  - "/nvme-ssd/yanyi/code/image/test/042.png"
  - "/nvme-ssd/yanyi/code/image/test/043.png"
  - "/nvme-ssd/yanyi/code/image/test/044.png"
  - "/nvme-ssd/yanyi/code/image/test/045.png"
  - "/nvme-ssd/yanyi/code/image/test/046.png"
  - "/nvme-ssd/yanyi/code/image/test/047.png"
  - "/nvme-ssd/yanyi/code/image/test/048.png"
  - "/nvme-ssd/yanyi/code/image/test/049.png"
  - "/nvme-ssd/yanyi/code/image/test/050.png"
  - "/nvme-ssd/yanyi/code/image/test/051.png"
  - "/nvme-ssd/yanyi/code/image/test/052.png"
  - "/nvme-ssd/yanyi/code/image/test/053.png"
  - "/nvme-ssd/yanyi/code/image/test/054.png"
  - "/nvme-ssd/yanyi/code/image/test/055.png"
  - "/nvme-ssd/yanyi/code/image/test/056.png"
  - "/nvme-ssd/yanyi/code/image/test/057.png"
  - "/nvme-ssd/yanyi/code/image/test/058.png"
  - "/nvme-ssd/yanyi/code/image/test/059.png"
  - "/nvme-ssd/yanyi/code/image/test/060.png"
  - "/nvme-ssd/yanyi/code/image/test/061.png"
  - "/nvme-ssd/yanyi/code/image/test/062.png"
  - "/nvme-ssd/yanyi/code/image/test/063.png"
  - "/nvme-ssd/yanyi/code/image/test/064.png"
  - "/nvme-ssd/yanyi/code/image/test/065.png"
  - "/nvme-ssd/yanyi/code/image/test/066.png"
  - "/nvme-ssd/yanyi/code/image/test/067.png"
  - "/nvme-ssd/yanyi/code/image/test/068.png"
  - "/nvme-ssd/yanyi/code/image/test/069.png"
  - "/nvme-ssd/yanyi/code/image/test/070.png"
  - "/nvme-ssd/yanyi/code/image/test/071.png"
  - "/nvme-ssd/yanyi/code/image/test/072.png"
  - "/nvme-ssd/yanyi/code/image/test/073.png"