seeds: 442

prompts:
  - "The left apple is rotting, the middle apple is turning green, the right apple is falling."
  - "The top flower is closing, the middle flower is turning red, the bottom flower is rotting."
  - "The left flower is closing, the middle flower is turning red, the right flower is rotting."
  - "The left cat is walking left, the middle cat is walking forward, the right cat is walking right."
  - "The left flower is closing, the middle flower is turning green, the right flower is rotting."
  - "The left girl is turning around, the middle girl is talking, the right girl is nodding."
  - "The left man is smiling, the middle man is nodding, the right man is opening his mouth wide."
  - "The left bird is flying downward, the top bird is flying upward, the bottom bird is flying to the right."
  - "The left flower is closing, the middle flower is turning green, the right flower is rotting."
  - "The left flower is rotting, the middle flower is turning green, the right flower is closing."
  - "The left sheep is walking left, the middle sheep is walking forward, the right sheep is walking right."
  - "The top duck is swimming upward, the middle duck is swimming forward, the bottom duck is swimming downward."
  - "The top heart is turning yellow, the middle heart is turning black, the bottom heart is turning green."
  - "The left woman is folding her arms, the middle woman is shaking her head, the right woman is nodding."
  - "The left girl is turning her head, the middle girl is talking, the right girl is raising her left hand."
  - "The left girl is turning her head, the middle girl is talking, the right girl is raising her right hand."
  - "The left boy is squatting, the middle girl is nodding, the right girl is turning around."
  - "The left red electric bicycle is moving left, the middle yellow electric bicycle is moving forward, the right blue electric bicycle is moving right."
  - "The left dandelion is scattering seeds, the middle dandelion is swaying, the right dandelion is withering."

n_prompts:
  - "nsfw, paintings, cartoon, anime, dark,sketches, wrong white balance,worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, extra claws,fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet,extrafeets,incongruousappearance,Distortedappearance,deformation,bad_pictures, negative_hand-neg , bad teeth, mutated hands and fingers, bad anatomy"
path_to_first_frames:
  - "/opt/data/private/data/three_modify/1.png"
  - "/opt/data/private/data/three_modify/2.png"
  - "/opt/data/private/data/three_modify/3.png"
  - "/opt/data/private/data/three_modify/4.png"
  - "/opt/data/private/data/three_modify/6.png"
  - "/opt/data/private/data/three_modify/7.png"
  - "/opt/data/private/data/three_modify/8.png"
  - "/opt/data/private/data/three_modify/9.png"
  - "/opt/data/private/data/three_modify/10.png"
  - "/opt/data/private/data/three_modify/11.png"
  - "/opt/data/private/data/three_modify/12.png"
  - "/opt/data/private/data/three_modify/13.png"
  - "/opt/data/private/data/three_modify/14.png"
  - "/opt/data/private/data/three_modify/15.png"
  - "/opt/data/private/data/three_modify/16.png"
  - "/opt/data/private/data/three_modify/17.png"
  - "/opt/data/private/data/three_modify/18.png"
  - "/opt/data/private/data/three_modify/19.png"
  - "/opt/data/private/data/three_modify/20.png"
