seeds: 442

prompts:
  - "a cat is nodding up and down,a dog is barking."
  - "a rabbit is chewing,a dog is barking."
  - "a chicken is nodding,a dog is barking."
  - "a dog is blinking its eyes,a girl is smiling."
  - "a dog is barking,a cat is downing head."
  - "a dog is barking,the fire hydrant is flowing water."
  - "a dog is barking,a cat is walking forward."
  - "a dog is barking,a cat is walking forward."
  - "a dog is noddding head,a cat is meowing."
  - "a dog is bowing head,a cat is shaking head."
  - "the left dog is falling down,the right dog is walking."
  - "a cat is wagging its tail,a dog is barking."
  - "a dog is nodding head,a cat is falling down."
  - "the left dog is nodding head,the right dog is barking."
  - "a dog is barking,a cat is sharking head."
  - "a cat is lifting its upper body,a dog is falling down."
  - "a dog is nodding head,a cat is meowing."
  - "a dog is nodding up and down,a cat is wagging tail."
  - "a cat is nodding up and down,a dog is falling down."
  - "a cat is walking forward,a dog is barking."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is shaking head."
  - "a dog is barking,a cat is falling down."
  - "a duck is nodding up and down,a cat is wagging tail."
  - "a duck is nodding,a pig is wagging tail."
  - "a girl is smiling,a boy is opening mouth."
  - "a girl is smiling,a boy is crying."
  - "a cat is walking,a dog is barking."
  - "a girl is smiling,a boy is shedding tears."
  - "a girl is smiling,a dog is sticking out its tongue."
  - "a woman is smiling,a baby is shedding tears."
  - "a woman is smiling,a dog is barking."
  - "a man is smiling,a woman is blinking her eyes."
  - "a cat is walking,a dog is barking."
  - "a rabbit is chewing,a dog is raising head."
  - "a dog is closing its mouth,a cat is meowing."
  - "a cat is meowing,a mouse is walking."
  - "a cat is meowing,a mouse is walking."
  - "a cat is meowing,a dog is nodding up and down."
  - "a cat is nodding,a dog is barking."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a chicken is turning back."
  - "a pig is wagging its tail,a dog is turning back."
  - "a dog is nodding head,a pig is raising head."
  - "a dog is barking,a cat is nodding head."
  - "a dog is barking,a cat is nodding head."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is nodding head."
  - "a woman is smiling,a dog is closing mouth."
  - "a woman is smiling,a dog is closing mouth."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a rabbit is chewing."
  - "a mouse is falling down,a dog is standing up."
  - "the left cat is nodding head,the right cat is walking."
  - "a cat is sleeping,a rabbit is chewing."
  - "a dog is barking,a duck is walking forward."
  - "a duck is shaking head,a dog is walking."
  - "a duck is nodding its head,a dog is barking."
  - "a dog is barking,a cat is walking forward."
  - "a girl is smiling,a duck is nodding its head."
  - "the left duck is nodding head,the right duck is walking."
  - "a dog is nodding head,a duck is quacking."
  - "a cat is meowing,a dog is sleeping."
  - "a duck is eating food,a pig is raising head."
  - "the left lion is roaring,the right lion is walking."
  - "a duck is quacking,a chicken is turning backing."
  - "a duck is standing up,a pig is barking."
  - "a pig is downing head,a dog is barking."
  - "a chicken is nodding head,a duck is walking."
  - "the left dog is barking,a right dog is falling down."
  - "a cat is walking,a dog is barking."
  - "a cat is walking,a dog is barking."
  - "a cat is downing head, a dog is barking."
  - "a dog is barking,a cat is walking forward."
  - "a dog is barking,a cat is nodding up and down."
  - "a cat is nodding up and down,a dog is barking."
  - "a dog is barking,a cat is smiling."
  - "a cat is walking forward,a dog is barking."
  - "a cat is meowing,a dog is walking forward."
  - "a cat is meowing,a dog is walking forward."
  - "a cat is nodding up and down,a dog is barking."
  - "a cat is downing head,a dog is smiling."
  - "a cat is meowing,a dog is shaking head."
  - "a dog is barking,a cat is falling down."
  - "a cat is lifting its head,a dog is barking."
  - "a dog is barking,a cat is wagging its tail."
  - "a dog is sleeping,a cat is meowing."
  - "a dog is sticking out its tongue,a cat is nodding head."
  - "a woman is smiling,a man is crying."
  - "a cat is lifting its head,a dog is barking."
  - "a woman is smiling,a man is crying."
  - "a dog is barking,a cat is walking."
  - "a cat is nodding head,a dog is walking."
  - "a dog is barking,a cat is falling down."
  - "a dog is barking,a cat is walking forward."
  - "a man is smilling,a woman is cryling."
  - "a cat is nodding head,a dog is walking."
  - "a dog is barking,a cat is walking forward."

n_prompts:
  - "nsfw, paintings, cartoon, anime, dark,sketches, wrong white balance,worst quality, low quality, normal quality, lowres, watermark, monochrome, grayscale, ugly, blurry, Tan skin, dark skin, black skin, skin spots, skin blemishes, age spot, glans, disabled, bad anatomy, amputation, bad proportions, twins, missing body, extra claws,fused body, extra head, poorly drawn face, bad eyes, deformed eye, unclear eyes, cross-eyed, long neck, malformed limbs, extra limbs, extra arms, missing arms, bad tongue, strange fingers, mutated hands, missing hands, poorly drawn hands, extra hands, fused hands, connected hand, bad hands, missing fingers, extra fingers, 4 fingers, 3 fingers, deformed hands, extra legs, bad legs, many legs, more than two legs, bad feet,extrafeets,incongruousappearance,Distortedappearance,deformation,bad_pictures, negative_hand-neg , bad teeth, mutated hands and fingers, bad anatomy"
path_to_first_frames:
  - "/opt/data/private/data/test_100/000.png"
  - "/opt/data/private/data/test_100/001.png"
  - "/opt/data/private/data/test_100/002.png"
  - "/opt/data/private/data/test_100/003.png"
  - "/opt/data/private/data/test_100/004.png"
  - "/opt/data/private/data/test_100/005.png"
  - "/opt/data/private/data/test_100/006.png"
  - "/opt/data/private/data/test_100/007.png"
  - "/opt/data/private/data/test_100/008.png"
  - "/opt/data/private/data/test_100/009.png"
  - "/opt/data/private/data/test_100/010.png"
  - "/opt/data/private/data/test_100/011.png"
  - "/opt/data/private/data/test_100/012.png"
  - "/opt/data/private/data/test_100/013.png"
  - "/opt/data/private/data/test_100/014.png"
  - "/opt/data/private/data/test_100/015.png"
  - "/opt/data/private/data/test_100/016.png"
  - "/opt/data/private/data/test_100/017.png"
  - "/opt/data/private/data/test_100/018.png"
  - "/opt/data/private/data/test_100/019.png"
  - "/opt/data/private/data/test_100/020.png"
  - "/opt/data/private/data/test_100/021.png"
  - "/opt/data/private/data/test_100/022.png"
  - "/opt/data/private/data/test_100/023.png"
  - "/opt/data/private/data/test_100/024.png"
  - "/opt/data/private/data/test_100/025.png"
  - "/opt/data/private/data/test_100/026.png"
  - "/opt/data/private/data/test_100/027.png"
  - "/opt/data/private/data/test_100/028.png"
  - "/opt/data/private/data/test_100/029.png"
  - "/opt/data/private/data/test_100/030.png"
  - "/opt/data/private/data/test_100/031.png"
  - "/opt/data/private/data/test_100/032.png"
  - "/opt/data/private/data/test_100/033.png"
  - "/opt/data/private/data/test_100/034.png"
  - "/opt/data/private/data/test_100/035.png"
  - "/opt/data/private/data/test_100/036.png"
  - "/opt/data/private/data/test_100/037.png"
  - "/opt/data/private/data/test_100/038.png"
  - "/opt/data/private/data/test_100/039.png"
  - "/opt/data/private/data/test_100/040.png"
  - "/opt/data/private/data/test_100/041.png"
  - "/opt/data/private/data/test_100/042.png"
  - "/opt/data/private/data/test_100/043.png"
  - "/opt/data/private/data/test_100/044.png"
  - "/opt/data/private/data/test_100/045.png"
  - "/opt/data/private/data/test_100/046.png"
  - "/opt/data/private/data/test_100/047.png"
  - "/opt/data/private/data/test_100/048.png"
  - "/opt/data/private/data/test_100/049.png"
  - "/opt/data/private/data/test_100/050.png"
  - "/opt/data/private/data/test_100/051.png"
  - "/opt/data/private/data/test_100/052.png"
  - "/opt/data/private/data/test_100/053.png"
  - "/opt/data/private/data/test_100/054.png"
  - "/opt/data/private/data/test_100/055.png"
  - "/opt/data/private/data/test_100/056.png"
  - "/opt/data/private/data/test_100/057.png"
  - "/opt/data/private/data/test_100/058.png"
  - "/opt/data/private/data/test_100/059.png"
  - "/opt/data/private/data/test_100/060.png"
  - "/opt/data/private/data/test_100/061.png"
  - "/opt/data/private/data/test_100/062.png"
  - "/opt/data/private/data/test_100/063.png"
  - "/opt/data/private/data/test_100/064.png"
  - "/opt/data/private/data/test_100/065.png"
  - "/opt/data/private/data/test_100/066.png"
  - "/opt/data/private/data/test_100/067.png"
  - "/opt/data/private/data/test_100/068.png"
  - "/opt/data/private/data/test_100/069.png"
  - "/opt/data/private/data/test_100/070.png"
  - "/opt/data/private/data/test_100/071.png"
  - "/opt/data/private/data/test_100/072.png"
  - "/opt/data/private/data/test_100/073.png"
  - "/opt/data/private/data/test_100/074.png"
  - "/opt/data/private/data/test_100/075.png"
  - "/opt/data/private/data/test_100/076.png"
  - "/opt/data/private/data/test_100/077.png"
  - "/opt/data/private/data/test_100/078.png"
  - "/opt/data/private/data/test_100/079.png"
  - "/opt/data/private/data/test_100/080.png"
  - "/opt/data/private/data/test_100/081.png"
  - "/opt/data/private/data/test_100/082.png"
  - "/opt/data/private/data/test_100/083.png"
  - "/opt/data/private/data/test_100/084.png"
  - "/opt/data/private/data/test_100/085.png"
  - "/opt/data/private/data/test_100/086.png"
  - "/opt/data/private/data/test_100/087.png"
  - "/opt/data/private/data/test_100/088.png"
  - "/opt/data/private/data/test_100/089.png"
  - "/opt/data/private/data/test_100/090.png"
  - "/opt/data/private/data/test_100/091.png"
  - "/opt/data/private/data/test_100/092.png"
  - "/opt/data/private/data/test_100/093.png"
  - "/opt/data/private/data/test_100/094.png"
  - "/opt/data/private/data/test_100/095.png"
  - "/opt/data/private/data/test_100/096.png"
  - "/opt/data/private/data/test_100/097.png"
  - "/opt/data/private/data/test_100/098.png"
  - "/opt/data/private/data/test_100/099.png"